# Generated by Django 5.0.7 on 2024-07-17 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TyPptCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_id", models.UUIDField(blank=True, default=None, null=True)),
                ("label", models.CharField(default="", max_length=64)),
                ("path", models.CharField(default="", max_length=1024)),
                ("status", models.CharField(default="sys_status.OK", max_length=64)),
                ("order_num", models.IntegerField(default=0)),
                ("remark", models.CharField(blank=True, default="", max_length=1024)),
                ("deleted_flag", models.BooleanField(default=False)),
                ("created_by", models.CharField(default="", max_length=64)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, default="", max_length=64)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_by", models.CharField(blank=True, default="", max_length=64)),
                ("deleted_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ty_ppt_catalog",
            },
        ),
    ]
