# Generated by Django 5.0.7 on 2024-07-23 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TyPptMain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=64)),
                ("lable", models.CharField(default="", max_length=64)),
                ("catalog", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(default="", max_length=1024)),
                ("type", models.CharField(default="", max_length=64)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("path", models.CharField(default="", max_length=1024)),
                ("status", models.CharField(default="sys_status.OK", max_length=64)),
                ("order_num", models.IntegerField(default=0)),
                ("remark", models.CharField(blank=True, default="", max_length=1024)),
                ("deleted_flag", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, default="", max_length=64)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, default="", max_length=64)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, default="", max_length=64)),
                ("deleted_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ty_ppt_main",
            },
        ),
        migrations.AlterField(
            model_name="typptcatalog",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="typptcatalog",
            name="parent_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
